### ISSUE TITLE
MIssing data load cmd?

### ISSUE THREAD

**Issue by jvoigts** [janelia-arduino/AD57X4R#1]
I'm using this code with a analog devices EVAL-AD5754REBZ here and I had to add an additional load command after setting the data registers, just another 0x1D0000, see p.25 of the datasheet.

Is there maybe some way to  configure the dac so that these are loaded automatically?

**Comment by peterpolidoro** [comment]
Hi. I modified the code to send the load command after every analogWrite. Is that what you mean? My changes compile, but I do not have a chip handy for testing. Can you please see if this fixes the issue and let me know? Thanks!
