### ISSUE TITLE
+-10V range setting is incorrect

### ISSUE THREAD

**Issue by jvoigts** [janelia-arduino/AD57X4R#2]
In the header, the bipolar 10V range is defined correctly( #define OUTPUT_RANGE_BIPOLAR_10V  0b100 ), but in setOutputRange, it's set to +-10.8V: https://github.com/janelia-arduino/AD57X4R/blob/e724c2aa77e86f338e0db7f983ec04d6f21f34de/src/AD57X4R.cpp#L280

**Comment by peterpolidoro** [comment]
I fixed this bug, but the bipolar analogWrite command is still not implemented properly yet.
