### ISSUE TITLE
not declared.....

### ISSUE THREAD

**Issue by Oh-Doo-Yong** [janelia-arduino/AD57X4R#3]
hello...

I try your example...
but build failed...

Error Message is...
=====================================================
AD57X4R.cpp: 78:40: error: void value not ignored as it ought to be
   unipolar_array_[channel_constrained] =
AD57X4R.cpp: In member function long int AD57X4R::getMinDacValue()
 
AD57X4R.cpp: 92:7: error: 'unipolar_' was not declared in this scope
   if (unipolar_)
AD57X4R.cpp: In member function long int AD57X4R::getMaxDacValue()
 
AD57X4R.cpp: 117:7: error: 'unipolar_' was not declared in this scope
   if (unipolar_)
AD57X4R.cpp: In member function void AD57X4R::setOutputRangeToChip(int, uint8_t, AD57X4R::Range)
 
AD57X4R.cpp: 341:7: error: 'unipolar_' was not declared in this scope
   unipolar_ = true
===================================================================

can you check your code....
Thank you very much..

**Comment by peterpolidoro** [comment]
Hi. Should be fixed now, sorry about that. I will be making some more improvements to the library next week.
