### ISSUE TITLE
Multi chip not working

### ISSUE THREAD

**Issue by jemtech** [janelia-arduino/AD57X4R#4]
Hi Peter,
thank you for this greate lib.

AD57X4R.cpp line 483:  void AD57X4R::writeMosiDatagramToChip

This method ignores the chip information. Multiple serial chained chips just doing th same.

Thank You
Jan-Erik

**Comment by peterpolidoro** [comment]
Hi. Why did you close this? Did you get it to work? I can take a look at it in the next few days if it still is not working.

**Comment by jemtech** [comment]
Hi, ich rewrote the code try to fix it. But the chips don't work the way I expect. I thought it might be impossible. But I will try also and may create a pull request.

**Comment by peterpolidoro** [comment]
Working on the fix now in another issue.
